services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    networks: 
      - frontend
  backtend:
    build: 
      context: ./backend
    ports:
      - "8080:80"
    networks: 
      - frontend
networks: 
  frontend: